In [ ]:
import json
import torch

from grace.run import run_grace
from grace.config import Config
from grace.models.feature_extractor import resnet

In [ ]:
LOG_DIR = "/Users/csoelistyo/Documents/grace_files/run_data"
IMAGE_DIR = "/Users/csoelistyo/Documents/grace_files/run_data/image_files"
GRACE_DIR = "/Users/csoelistyo/Documents/grace_files/run_data/grace_files"
CONFIG_FILE = "/Users/csoelistyo/Documents/grace_files/run_data/run_config.json"

#### If no extractor model file exists yet

In [ ]:
EXTRACTOR_FN = '/Users/csoelistyo/Documents/grace_files/run_data/extractor.pt'
extractor = resnet()
torch.save(extractor, EXTRACTOR_FN)

#### If no config file exists yet

In [ ]:
config = Config(
    image_dir=IMAGE_DIR,
    grace_dir=GRACE_DIR,
    log_dir=LOG_DIR,
)
json.dump(config.__dict__, open(CONFIG_FILE, 'w'))

#### Run

In [ ]:
run_grace(CONFIG_FILE)

In [1]:
FN = '/Users/csoelistyo/Documents/grace_files/image_2/MRC_Synthetic_File_006.grace/annotation.npz'

In [3]:
import numpy as np
j = np.load(FN)

In [8]:
FN = '/Users/csoelistyo/Documents/grace_files/image_dir_test/FoilHole_24680421_Data_24671727_24671728_20181024_2216-78563_noDW.mrc'

In [10]:
import mrcfile

with mrcfile.open(FN, 'r') as mrc:
    print(mrc.data.dtype)

float32


In [11]:
image = np.zeros((5,5,), dtype='uint16')

In [20]:
import torch

j = torch.tensor(image, dtype=torch.float32)

TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [21]:
from grace.models.classifier import GCN

In [25]:
gcn = GCN(
    input_channels=8,
    hidden_channels=[3, 3]
)

In [26]:
list(gcn.parameters())

[Parameter containing:
 tensor([[-0.2331,  0.3558,  0.0896],
         [ 0.3665,  0.4889, -0.1503]], requires_grad=True),
 Parameter containing:
 tensor([0.2253, 0.4507], requires_grad=True),
 Parameter containing:
 tensor([[ 0.1918,  0.0325,  0.3936,  0.3663,  0.1028, -0.3732],
         [ 0.2774,  0.2829, -0.4006,  0.1727, -0.1301, -0.1262]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.3034, -0.3822], requires_grad=True)]

In [ ]:
x = np.random.uniform()